[package]
name = "wifibf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wifibf"
path = "src/main.rs"

[dependencies]
eframe = "0.31"
egui = "0.31"
rfd = "0.15"

[target.'cfg(windows)'.dependencies.windows]
version = "0.58"
features = [
    "Win32_NetworkManagement_WiFi",
    "Win32_NetworkManagement_Ndis",
    "Win32_Foundation",
    "Win32_Security",
]

